spring.application.name=ms_facturacion

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3312/pedidos360_facturacion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=pedidos360
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVIDOR
# ===============================

server.port=8086

# ===============================
# RABBITMQ
# ===============================

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin